baseURL = "https://example.com"

theme = "LoveIt"

title = "Yu an Ai"

defaultContentLanguage = "ja"
languageCode = "ja"

hasCJKLanguage = true

# whether to use robots.txt
enableRobotsTXT = true

# whether to use emoji code
enableEmoji = true

# Gitコミットの最新日時をlastmod（更新日）に反映
enableGitInfo = true

# Author config
[author]
  name = "xhuAi"
  email = ""
  link = ""


# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = ""
    post = ""
    name = "Post"
    url = "/posts/"
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tag"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""


[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "auto"

  # date format
  dateFormat = "2006-01-02"

  # website title for Open Graph and Twitter Cards
  title = "citrus1998"

  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "Hugo theme - LoveIt"

  # website images for Open Graph and Twitter Cards
  images = ["/myicon.jpg"]


  # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"

    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"

    # Header title config
    [params.header.title]
      # title name
      name = "Yu an Ai"

      # whether to use typeit animation for title name
      typeit = false


  # Footer config
  [params.footer]
    enable = true

    # whether to show Hugo and theme info
    hugo = false

    # whether to show copyright info
    copyright = true

    # whether to show the author
    author = true

    # site creation time
    since = 2022
    
    # license info (HTML format is supported)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20

    # date format (month and day)
    dateFormat = "01-02"

    # amount of RSS pages
    rss = 10

  # App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "LoveIt"

    # whether to omit favicon resource links
    noFavicon = false

    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = "/images/myicon.jpg"

    # Android browser theme color
    themeColor = "#ffffff"

    # Safari mask icon color
    iconColor = "#5bbad5"

    # Windows v8-11 tile color
    tileColor = "#da532c"

  # Search config
  [params.search]
    enable = true

    # type of search engine ["lunr", "algolia"]
    type = "algolia"

    # max index length of the chunked content
    contentLength = 4000

    # placeholder of the search bar
    placeholder = ""

    # max number of results length
    maxResultLength = 10

    # snippet length of the result
    snippetLength = 30

    # HTML tag name of the highlight part in results
    highlightTag = "em"

    # whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  # Home page config
  [params.home]

    # amount of RSS pages
    rss = 10

    # Home page profile
    [params.home.profile]
      enable = true

      # URL of avatar shown in home page
      avatarURL = "images/myicon.jpg"

      # title shown in home page (HTML format is supported)
      title = ""

      # subtitle shown in home page (HTML format is supported)
      #subtitle = ""

      # whether to use typeit animation for subtitle
      typeit = true

      # whether to show social links
      social = true

      # disclaimer (HTML format is supported)
      disclaimer = ""

    # Home page posts
    [params.home.posts]
      enable = true

      # date format (month and day)
       dateFormat = "01-02"

      # special amount of posts in each home posts page
      paginate = 6

  # Page global config
  [params.page]
    # whether to hide a page from home page
    hiddenFromHomePage = false

    # whether to hide a page from search results
    hiddenFromSearch = false

    # whether to enable twemoji
    twemoji = false

    # whether to enable lightgallery
    lightgallery = false

    # whether to enable the ruby extended syntax
    ruby = true

    # whether to enable the fraction extended syntax
    fraction = true

    # whether to enable the fontawesome extended syntax
    fontawesome = true

    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true

    # whether to show the full text content in RSS
    rssFullText = false

    # Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true

      # whether to keep the static table of the contents in front of the post
      keepStatic = false

      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true

    # Code config
    [params.page.code]
      # whether to show the copy button of the code block
      copy = true

      # the maximum number of lines of displayed code by default
      maxShownLines = 50

    # KaTeX mathematical formulas config (KaTeX https://katex.org/)
    [params.page.math]
      enable = false

      # default inline delimiter is $ ... $ and \( ... \)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""

      # default block delimiter is $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} and some other functions
      blockLeftDelimiter = ""
      blockRightDelimiter = ""

      # KaTeX extension copy_tex
      copyTex = true

      # KaTeX extension mhchem
      mhchem = true

    # Social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      HackerNews = true
      Reddit = false
      Weibo = true
      Blogger = false
      Baidu = false
      Evernote = false
      Trello = false

  # Analytics config
  [params.analytics]
    enable = false

    # Google Analytics
    [params.analytics.google]
      id = ""

      # whether to anonymize IP
      anonymizeIP = true

    # Fathom Analytics
    [params.analytics.fathom]
      id = ""

      # server url for your tracker if you're self hosting
      server = ""

    # Plausible Analytics
    [params.analytics.plausible]
      dataDomain = ""

  # Cookie consent config
  [params.cookieconsent]
    enable = false
    # text strings used for Cookie consent banner
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

  # CDN config for third-party library files
  [params.cdn]
    # CDN data file name, disabled by default
    # ["jsdelivr.yml"]
    # located in "themes/LoveIt/assets/data/cdn/" directory
    # you can store your own data files in the same path under your project:
    # "assets/data/cdn/"
    data = "jsdelivr.yml"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true

    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true

    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true

  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]


# Multilingual
# 多语言
[languages]
  [languages.ja]
    weight = 1
    languageCode = "ja"
    languageName = "日本語"
    hasCJKLanguage = true
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [languages.ja.menu]
      [[languages.ja.menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "記事一覧"
        url = "/posts/"
        title = ""
      [[languages.ja.menu.main]]
        weight = 2
        identifier = "tags"
        pre = ""
        post = ""
        name = "タグ"
        url = "/tags/"
        title = ""
      [[languages.ja.menu.main]]
        weight = 3
        identifier = "categories"
        pre = ""
        post = ""
        name = "カテゴリー"
        url = "/categories/"
        title = ""
      [[languages.ja.menu.main]]
        weight = 4
        identifier = "about"
        pre = ""
        post = ""
        name = "このサイトについて"
        url = "/about/"
        title = ""
      [[languages.ja.menu.main]]
        weight = 5
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
        post = ""
        name = ""
        url = "https://github.com/citrus1998/"
        title = "GitHub"
    [languages.ja.params]
      [languages.ja.params.search]
        enable = true
        type = "algolia"
        contentLength = 4000
        placeholder = ""
        maxResultLength = 10
        snippetLength = 30
        highlightTag = "em"
        absoluteURL = false
        [languages.ja.params.search.algolia]
          index = "index.ja"
          appID = ""
          searchKey = ""
      [languages.ja.params.home]
        rss = 10
        [languages.ja.params.home.profile]
          enable = false
          gravatarEmail = ""
          avatarURL = "/images/myicon.jpg"
          title = ""
          subtitle = "自由に投稿します．宜しくお願い致します．"
          typeit = true
          social = true
          disclaimer = ""
      [languages.ja.params.social]
        GitHub = "citrus1998"
        Twitter = "citrus1998"
        #Instagram = "xxxx"
        #Facebook = "xxxx"
        #Telegram = "xxxx"
        #Youtubelegacy = "xxxx"
        #Phone = "555-555-555"
        #Email = "xxxx@xxxx.com"
        RSS = true
        #[languages.ja.params.social.Mastodon]
        #  id = "@xxxx"
        #  prefix = "https://mastodon.technology/"

  [languages.en]
    weight = 2
    languageCode = "en"
    languageName = "English"
    hasCJKLanguage = false
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [languages.en.menu]
      [[languages.en.menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
      [[languages.en.menu.main]]
        weight = 2
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
      [[languages.en.menu.main]]
        weight = 3
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
      [[languages.en.menu.main]]
        weight = 4
        identifier = "about"
        pre = ""
        post = ""
        name = "About"
        url = "/about/"
        title = ""
      [[languages.en.menu.main]]
        weight = 5
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
        post = ""
        name = ""
        url = "https://github.com/citrus1998/"
        title = "GitHub"
    [languages.en.params]
      [languages.en.params.search]
        enable = true
        type = "algolia"
        contentLength = 4000
        placeholder = ""
        maxResultLength = 10
        snippetLength = 30
        highlightTag = "em"
        absoluteURL = false
        [languages.en.params.search.algolia]
          index = "index.en"
          appID = "PASDMWALPK"
          searchKey = "b42948e51daaa93df92381c8e2ac0f93"
      [languages.en.params.home]
        rss = 10
        [languages.en.params.home.profile]
          enable = false
          gravatarEmail = ""
          avatarURL = "/images/myicon.jpg"
          title = ""
          subtitle = "Hi, I'll post any articles freely. Nice to meet you."
          typeit = true
          social = true
          disclaimer = ""
      [languages.en.params.social]
        GitHub = "citrus1998"
        Twitter = "citrus1998"
        #Instagram = "xxxx"
        #Facebook = "xxxx"
        #Telegram = "xxxx"
        #Youtubelegacy = "xxxx"
        #Phone = "555-555-555"
        #Email = "xxxx@xxxx.com"
        RSS = true
        #[languages.en.params.social.Mastodon]
        #  id = "@xxxx"
        #  prefix = "https://mastodon.technology/"

  [languages.zh-cn]
    weight = 3
    languageCode = "zh-CN"
    languageName = "简体中文"
    hasCJKLanguage = true
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "所有文章"
        url = "/posts/"
        title = ""
      [[languages.zh-cn.menu.main]]
        weight = 2
        identifier = "tags"
        pre = ""
        post = ""
        name = "标签"
        url = "/tags/"
        title = ""
      [[languages.zh-cn.menu.main]]
        weight = 3
        identifier = "categories"
        pre = ""
        post = ""
        name = "分类"
        url = "/categories/"
        title = ""
      [[languages.zh-cn.menu.main]]
        weight = 4
        identifier = "about"
        pre = ""
        post = ""
        name = "关于"
        url = "/about/"
        title = ""
      [[languages.zh-cn.menu.main]]
        weight = 5
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
        post = ""
        name = ""
        url = "https://github.com/citrus1998/"
        title = "GitHub"
    [languages.zh-cn.params]
      [languages.zh-cn.params.search]
        enable = true
        type = "algolia"
        contentLength = 4000
        placeholder = ""
        maxResultLength = 10
        snippetLength = 50
        highlightTag = "em"
        absoluteURL = false
        [languages.zh-cn.params.search.algolia]
          index = "index.zh-cn"
          appID = "PASDMWALPK"
          searchKey = "b42948e51daaa93df92381c8e2ac0f93"
      [languages.zh-cn.params.home]
        rss = 10
        [languages.zh-cn.params.home.profile]
          enable = false
          gravatarEmail = ""
          avatarURL = "/images/myicon.jpg"
          title = ""
          subtitle = "我会免费发布任何文章.很高兴见到你."
          typeit = true
          social = true
          disclaimer = ""
      [languages.zh-cn.params.social]
        GitHub = "citrus1998"
        #Weibo = "xxxx"
        #Steam = "xxxx"
        #Zhihu = "xxxx"
        #Douban = "xxxx"
        #Devto = "xxxx"
        #Bilibili = "xxxx"
        #Email = "xxxx@xxxx.com"
        #Phone = "555-555-555"
        RSS = true

